linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: -1
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - rangeValCopy
      - hugeParam
  gocyclo:
    min-complexity: 15
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: gitlab.app.cube/medcore/
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '42'
  revive:
    rules:
      - name: var-naming
        disabled: true
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: "ST1003:"

    - linters:
        - staticcheck
      text: "SA1019:"

    - path: _test\.go
      linters:
        - mnd
        - gocritic
run:
  timeout: 5m